reddit:
  client_id: ${REDDIT_CLIENT_ID}
  client_secret: ${REDDIT_CLIENT_SECRET}

mistral:
  api_key: "cRfO3lC8vaQ8rvcyqapOjvFRs5Ntn3xV"
  model: "mistral-medium-latest"

database:
  type: sqlite
  dbname: ../ideadb-web/ideadb.db

crawler:
  subreddits:
    - SideProject
    - Entrepreneur
    - problems
    # - smallbusiness
    - startups
    # - Business_Ideas
    # - roastmystartup
    # - buildinpublic
  post_limit: 10
  rate_limit_secs: 2
  sharing_keywords:
    - "share what you're building"
    - "share what you are building"
    - "show off your project"
    - "what are you working on"
    - "showcase"
    - "share your startup"
    - "show your side project"
    - "monthly self promotion"
